[main] - teste deploy 3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,15 @@ jobs:
             fi
             cd /data/GuNaBackend
             git pull origin main
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm not found at $NVM_DIR"
+              exit 1
+            fi
+            nvm install 24
+            nvm use 24
             npm ci
             npm run build
             if pm2 describe gunabackend >/dev/null; then
